export default Data= [
    {
        "id": "info01",
        "team": "I",
        "control": "combobox",
        "dataType": null,
        "dataSource": "120",
        "caption": "Chứng chỉ",
        "requireSubmit": "1",
        "parent": null,
        "sort": 10,
        "value": null,
        "display": null
    },
    {
        "id": "info02",
        "team": "I",
        "control": "textedit",
        "dataType": "text(4)",
        "dataSource": null,
        "caption": "Tên chứng chỉ",
        "requireSubmit": "1",
        "parent": null,
        "sort": 20,
        "value": null,
        "display": null
    },
    {
        "id": "info03",
        "team": "I",
        "control": "combobox",
        "dataType": null,
        "dataSource": "119",
        "caption": "Xếp loại",
        "requireSubmit": "0",
        "parent": null,
        "sort": 30,
        "value": null,
        "display": null
    },
    {
        "id": "info04",
        "team": "I",
        "control": "combobox",
        "dataType": null,
        "dataSource": "118",
        "caption": "Trường/Nơi cấp",
        "requireSubmit": "0",
        "parent": null,
        "sort": 40,
        "value": null,
        "display": null
    },
    {
        "id": "info05",
        "team": "I",
        "control": "combobox",
        "dataType": null,
        "dataSource": "115",
        "caption": "Chuyên ngành",
        "requireSubmit": "0",
        "parent": null,
        "sort": 50,
        "value": null,
        "display": null
    },
    {
        "id": "info06",
        "team": "I",
        "control": "combobox",
        "dataType": null,
        "dataSource": "116",
        "caption": "Hình thức đào tạo",
        "requireSubmit": "0",
        "parent": null,
        "sort": 60,
        "value": null,
        "display": null
    },
    {
        "id": "info08",
        "team": "I",
        "control": "datepicker",
        "dataType": "date",
        "dataSource": null,
        "caption": "Ngày cấp bằng",
        "requireSubmit": "0",
        "parent": null,
        "sort": 80,
        "value": null,
        "display": null
    },
    {
        "id": "info09",
        "team": "I",
        "control": "datepicker",
        "dataType": "date",
        "dataSource": null,
        "caption": "Hiệu lực từ",
        "requireSubmit": "0",
        "parent": null,
        "sort": 90,
        "value": null,
        "display": null
    },
    {
        "id": "info10",
        "team": "I",
        "control": "datepicker",
        "dataType": "date",
        "dataSource": null,
        "caption": "Hiệu lực đến",
        "requireSubmit": "0",
        "parent": null,
        "sort": 100,
        "value": null,
        "display": null
    }
]