export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const DID_LOGIN_ACTION = 'DID_LOGIN_ACTION';

export const POST_LOGIN = 'POST_LOGIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

//UserInfo
export const GET_PRIVATE_ALLOW = 'GET_PRIVATE_ALLOW';
export const GET_PRIVATE_ALLOW_SUCCESS = 'GET_PRIVATE_ALLOW_SUCCESS';
export const GET_PRIVATE_ALLOW_ERROR = 'GET_PRIVATE_ALLOW_ERROR';

export const SUBMIT_PRIVATE_GENERAL = 'SUBMIT_PRIVATE_GENERAL'
export const SUBMIT_PRIVATE_GENERAL_SUCCESS = 'SUBMIT_PRIVATE_GENERAL_SUCCESS'
export const SUBMIT_PRIVATE_GENERAL_ERROR = 'SUBMIT_PRIVATE_GENERAL_ERROR'

export const GET_PRIVATE_VIEW = 'GET_PRIVATE_VIEW';
export const GET_PRIVATE_VIEW_SUCCESS = 'GET_PRIVATE_VIEW_SUCCESS';
export const GET_PRIVATE_VIEW_ERROR = 'GET_PRIVATE_VIEW_ERROR';

export const GET_PRIVATE_PROFILE = 'GET_PRIVATE_PROFILE';
export const GET_PRIVATE_PROFILE_SUCCESS = 'GET_PRIVATE_PROFILE_SUCCESS';
export const GET_PRIVATE_PROFILE_ERROR = 'GET_PRIVATE_PROFILE_ERROR';

export const GET_PRIVATE_GENERAL = 'GET_PRIVATE_GENERAL';
export const GET_PRIVATE_GENERAL_SUCCESS = 'GET_PRIVATE_GENERAL_SUCCESS';
export const GET_PRIVATE_GENERAL_ERROR = 'GET_PRIVATE_GENERAL_ERROR';

export const GET_PERSONAL_FORM_LIST = 'GET_PERSONAL_FORM_LIST';
export const GET_PERSONAL_FORM_LIST_SUCCESS = 'GET_PERSONAL_FORM_LIST_SUCCESS';
export const GET_PERSONAL_FORM_LIST_ERROR = 'GET_PERSONAL_FORM_LIST_ERROR';

export const GET_PRIVATE_FORM = 'GET_PRIVATE_FORM';
export const GET_PRIVATE_FORM_SUCCESS = 'GET_PRIVATE_FORM_SUCCESS';
export const GET_PRIVATE_FORM_ERROR = 'GET_PRIVATE_FORM_ERROR';

export const GET_PRIVATE_LIST = 'GET_PRIVATE_LIST';
export const GET_PRIVATE_LIST_SUCCESS = 'GET_PRIVATE_LIST_SUCCESS';
export const GET_PRIVATE_LIST_ERROR = 'GET_PRIVATE_LIST_ERROR';

export const SAVE_PRIVATE_FORM = 'SAVE_PRIVATE_FORM';
export const SAVE_PRIVATE_FORM_SUCCESS = 'SAVE_PRIVATE_FORM_SUCCESS';
export const SAVE_PRIVATE_FORM_ERROR = 'SAVE_PRIVATE_FORM_ERROR';

export const DELETE_PRIVATE_FORM = 'DELETE_PRIVATE_FORM';
export const DELETE_PRIVATE_FORM_SUCCESS = 'DELETE_PRIVATE_FORM_SUCCESS';
export const DELETE_PRIVATE_FORM_ERROR = 'DELETE_PRIVATE_FORM_ERROR';

export const POPUP_POST_LOGIN = 'POPUP_POST_LOGIN';
export const POPUP_POST_LOGIN_SUCCESS = 'POPUP_POST_LOGIN_SUCCESS';
export const POPUP_POST_LOGIN_FAILED = 'POPUP_POST_LOGIN_FAILED';

export const POPUP_POST_LOGIN_SHOW = 'POPUP_POST_LOGIN_SHOW';
export const POPUP_POST_LOGIN_HIDE = 'POPUP_POST_LOGIN_HIDE';

export const POPUP_CALL_RESET_ALL_REDUCERS = 'POPUP_CALL_RESET_ALL_REDUCERS';

export const POPUP_ALERT = 'POPUP_ALERT';
export const POPUP_ALERT_SHOW = 'POPUP_ALERT_SHOW';
export const POPUP_ALERT_HIDE = 'POPUP_ALERT_HIDE';


export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS';
export const UPLOAD_AVATAR_FAILED = 'UPLOAD_AVATAR_FAILED';

export const REPLACE_SCREEN_LOGIN = 'REPLACE_SCREEN_LOGIN'
export const REPLACE_SCREEN_LOGIN_ACTION = 'REPLACE_SCREEN_LOGIN_ACTION'

export const POPUP_UPDATE_APP_SHOW = 'POPUP_UPDATE_APP_SHOW';


export const DELETE_TOKEN_NOTI_ACTION = 'DELETE_TOKEN_NOTI_ACTION';
export const DELETE_TOKEN_NOTI_ACTION_SUCCESS = 'DELETE_TOKEN_NOTI_ACTION_SUCCESS';
export const DELETE_TOKEN_NOTI_ACTION_FAILED = 'DELETE_TOKEN_NOTI_ACTION_FAILED';

