export const SEND_ACCOUNT_FORGOT_PASSWORD = 'SEND_ACCOUNT_FORGOT_PASSWORD';
export const SEND_ACCOUNT_FORGOT_PASSWORD_SUCCESS = 'SEND_ACCOUNT_FORGOT_PASSWORD_SUCCESS';
export const SEND_ACCOUNT_FORGOT_PASSWORD_FAILED = 'SEND_ACCOUNT_FORGOT_PASSWORD_FAILED';


export const SEND_CODE_VERIFY_FORGOT_PASSWORD = 'SEND_CODE_VERIFY_FORGOT_PASSWORD';
export const SEND_CODE_VERIFY_FORGOT_PASSWORD_SUCCESS = 'SEND_CODE_VERIFY_FORGOT_PASSWORD_SUCCESS';
export const SEND_CODE_VERIFY_FORGOT_PASSWORD_FAILED = 'SEND_CODE_VERIFY_FORGOT_PASSWORD_FAILED';


export const sendAccountForgotPasswordActions = (input) => {
    return {
      type: SEND_ACCOUNT_FORGOT_PASSWORD,
      input
    }
}
  


export const sendCodeVerifyForgotPasswordActions = (input) => {
    return {
      type: SEND_CODE_VERIFY_FORGOT_PASSWORD,
      input
    }
}