export const APPLICATION_APPROVAL_ACTION = 'APPLICATION_APPROVAL_ACTION'
export const APPLICATION_APPROVAL_ACTION_SUCCESS = 'APPLICATION_APPROVAL_ACTION_SUCCESS'
export const APPLICATION_APPROVAL_ACTION_FAILED = 'APPLICATION_APPROVAL_ACTION_FAILED'
export const RESET_APPLICATION_APPROVAL_ACTION = 'RESET_APPLICATION_APPROVAL_ACTION'

export const applicationApprovalAction = (input) => {
    return {
        type: APPLICATION_APPROVAL_ACTION,
        input
    }
}

export const resetApplicationApprovalAction = () => {
    return {
        type: RESET_APPLICATION_APPROVAL_ACTION
    }
}




export const GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION = 'GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION'
export const GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION_SUCCESS = 'GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION_SUCCESS'
export const GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION_ERROR = 'GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION_ERROR'


export const getListCheckInOutGPSApplicationAction = (input) => {
    return {
        type: GET_LIST_CHECK_INOUT_GPS_APPLICATION_ACTION,
        input
    };
};
